/**
 * 播報總控台 — 完整功能版
 * - 訂閱 voidRankingsUpdate CustomEvent 自動接收排名
 * - 呼叫 /api/v1/system/broadcast 生成播報稿
 * - 語音播報（Web Speech API）
 * - 播報稿可即時編輯後再複製
 * - 自動儲存至 localStorage，重新整理後仍保留
 */
import { useState, useEffect, useCallback, useRef } from 'react';
import { Radio, RefreshCw, Copy, Check, Mic, MicOff, Edit3, Save } from 'lucide-react';

interface RankRow {
  rank: number;
  name: string;
  amount: number;
  group?: string;
}

interface BroadcastScript {
  script: string;
  reportDate: string;
  personCount: number;
  generatedAt: string;
}

const LS_KEY = 'broadcastScript';

export function BroadcastPage() {
  const [rankings, setRankings] = useState<RankRow[]>([]);
  const [reportDate, setReportDate] = useState('');
  const [script, setScript] = useState<BroadcastScript | null>(null);
  const [editText, setEditText] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [speaking, setSpeaking] = useState(false);
  const [lastUpdated, setLastUpdated] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // ── 初始：從 localStorage 恢復上次播報稿 ──
  useEffect(() => {
    try {
      const savedScript = localStorage.getItem(LS_KEY);
      if (savedScript) {
        const parsed: BroadcastScript = JSON.parse(savedScript);
        setScript(parsed);
        setEditText(parsed.script);
      }
      const savedRankings = localStorage.getItem('voidRankings');
      if (savedRankings) {
        const parsed = JSON.parse(savedRankings);
        if (parsed.rows?.length) {
          setRankings(parsed.rows);
          const now = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Taipei' }).format(new Date());
          setReportDate(now);
          setLastUpdated(new Date(parsed.updatedAt).toLocaleTimeString('zh-TW', { hour12: false }));
        }
      }
    } catch { /* 忽略 */ }
  }, []);

  // ── 監聽 voidRankingsUpdate — 自動更新並重新生成 ──
  useEffect(() => {
    async function onUpdate(e: Event) {
      const ev = e as CustomEvent<{ rows: RankRow[]; updatedAt: number }>;
      if (!ev.detail?.rows?.length) return;
      setRankings(ev.detail.rows);
      const now = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Taipei' }).format(new Date());
      setReportDate(now);
      setLastUpdated(new Date(ev.detail.updatedAt).toLocaleTimeString('zh-TW', { hour12: false }));
      // 自動生成播報稿
      setAutoGenerated(false);
      try {
        const res = await fetch('/api/v1/system/broadcast', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ rankings: ev.detail.rows, reportDate: now }),
        });
        const json = await res.json();
        if (json.success) {
          setScript(json.data);
          setEditText(json.data.script);
          setAutoGenerated(true);
          localStorage.setItem(LS_KEY, JSON.stringify(json.data));
        }
      } catch { /* 靜默 */ }
    }
    window.addEventListener('voidRankingsUpdate', onUpdate);
    return () => window.removeEventListener('voidRankingsUpdate', onUpdate);
  }, []);

  const generate = useCallback(async () => {
    if (!rankings.length) {
      setError('❌ 尚無排名資料，請先在業績黑洞頁送出資料');
      return;
    }
    setLoading(true);
    setError('');
    setIsEditing(false);
    try {
      const res = await fetch('/api/v1/system/broadcast', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ rankings, reportDate }),
      });
      const json = await res.json();
      if (json.success) {
        setScript(json.data);
        setEditText(json.data.script);
        localStorage.setItem(LS_KEY, JSON.stringify(json.data));
      } else {
        setError(json.message || '生成失敗');
      }
    } catch {
      setError('❌ 無法連線後端');
    } finally {
      setLoading(false);
    }
  }, [rankings, reportDate]);

  const displayText = isEditing ? editText : (script?.script ?? '');

  const copyScript = useCallback(() => {
    if (!displayText) return;
    navigator.clipboard.writeText(displayText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [displayText]);

  const speak = useCallback(() => {
    if (!displayText) return;
    if (speaking) {
      window.speechSynthesis.cancel();
      setSpeaking(false);
      return;
    }
    const utter = new SpeechSynthesisUtterance(displayText);
    utter.lang = 'zh-TW';
    utter.rate = 0.88;
    utter.pitch = 1.05;
    utter.onend = () => setSpeaking(false);
    utter.onerror = () => setSpeaking(false);
    window.speechSynthesis.speak(utter);
    setSpeaking(true);
  }, [displayText, speaking]);

  const saveEdit = useCallback(() => {
    if (!script) return;
    const updated = { ...script, script: editText };
    setScript(updated);
    localStorage.setItem(LS_KEY, JSON.stringify(updated));
    setIsEditing(false);
  }, [script, editText]);

  // A1/A2/B/C 各組人數
  const groupCounts = ['A1', 'A2', 'B', 'C'].reduce((acc, g) => {
    acc[g] = rankings.filter(r => r.group === g).length;
    return acc;
  }, {} as Record<string, number>);

  return (
    <div className="max-w-3xl mx-auto space-y-5 p-6 animate-in fade-in slide-in-from-bottom-4 duration-500">

      {/* 標題 */}
      <div className="pb-4 border-b border-gray-200">
        <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
          <Radio className="w-7 h-7 text-purple-500" /> 播報總控台
        </h1>
        <p className="text-gray-500 mt-1 text-sm">
          {lastUpdated
            ? <><span className="text-green-600 font-semibold">● 即時連線</span> — 已從業績黑洞接收 {rankings.length} 筆排名（{lastUpdated} 更新）{autoGenerated && <span className="ml-2 text-purple-500 text-xs">✦ 已自動生成播報稿</span>}</>
            : '等待業績資料輸入…請先在業績黑洞頁送出排名'}
        </p>
      </div>

      {/* 分組快覽 */}
      {rankings.length > 0 && (
        <div className="grid grid-cols-4 gap-2">
          {(['A1', 'A2', 'B', 'C'] as const).map(g => (
            <div key={g} className="rounded-xl border p-3 text-center bg-purple-50 border-purple-100">
              <p className="text-base font-bold text-purple-700">{g}</p>
              <p className="text-xs text-purple-500 mt-0.5">{groupCounts[g] || 0} 人</p>
            </div>
          ))}
        </div>
      )}

      {/* 錯誤 */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-sm text-red-700">{error}</div>
      )}

      {/* 操作列 */}
      <div className="flex gap-3 flex-wrap">
        <button
          onClick={generate}
          disabled={loading || !rankings.length}
          className="flex items-center gap-2 px-5 py-2.5 text-sm font-bold text-white bg-gradient-to-r from-purple-600 to-indigo-600 rounded-xl shadow-md transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Radio className="w-4 h-4" />}
          {loading ? '生成中…' : script ? '重新生成' : '生成播報稿'}
        </button>

        {script && (
          <>
            <button
              onClick={speak}
              className={`flex items-center gap-2 px-5 py-2.5 text-sm font-semibold rounded-xl border transition-all active:scale-95 ${speaking ? 'bg-red-50 border-red-200 text-red-600' : 'bg-purple-50 border-purple-200 text-purple-700 hover:bg-purple-100'}`}
            >
              {speaking ? <MicOff className="w-4 h-4" /> : <Mic className="w-4 h-4" />}
              {speaking ? '停止播報' : '語音播報'}
            </button>

            <button
              onClick={() => { setIsEditing(v => !v); if (!isEditing) setTimeout(() => textareaRef.current?.focus(), 50); }}
              className="flex items-center gap-2 px-5 py-2.5 text-sm font-semibold rounded-xl border border-gray-200 text-gray-700 bg-white hover:bg-gray-50 transition-all active:scale-95"
            >
              <Edit3 className="w-4 h-4" />
              {isEditing ? '取消編輯' : '編輯播報稿'}
            </button>

            <button
              onClick={copyScript}
              className="flex items-center gap-2 px-5 py-2.5 text-sm font-semibold rounded-xl border border-gray-200 text-gray-700 bg-white hover:bg-gray-50 transition-all active:scale-95"
            >
              {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
              {copied ? '已複製！' : '複製播報稿'}
            </button>
          </>
        )}
      </div>

      {/* 播報稿輸出 */}
      {script && (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="px-5 py-3 border-b border-gray-100 bg-gray-50/80 flex items-center justify-between flex-wrap gap-2">
            <div className="font-semibold text-gray-800 flex items-center gap-2 text-sm">
              <Radio className="w-4 h-4 text-purple-500" />
              播報稿 — {script.personCount} 人 · {script.reportDate}
              {isEditing && <span className="text-xs text-orange-500 font-normal ml-1">（編輯模式）</span>}
            </div>
            {isEditing && (
              <button
                onClick={saveEdit}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-all"
              >
                <Save className="w-3.5 h-3.5" /> 儲存修改
              </button>
            )}
          </div>
          <div className="p-5">
            {isEditing ? (
              <textarea
                ref={textareaRef}
                value={editText}
                onChange={e => setEditText(e.target.value)}
                className="w-full text-sm text-gray-800 font-sans leading-relaxed bg-gray-50 border border-gray-200 rounded-xl p-4 outline-none focus:ring-2 focus:ring-purple-400 resize-none"
                rows={Math.max(10, editText.split('\n').length + 2)}
              />
            ) : (
              <pre className="text-sm text-gray-800 whitespace-pre-wrap font-sans leading-relaxed">
                {script.script}
              </pre>
            )}
            <p className="text-xs text-gray-400 mt-4">
              生成時間：{script.generatedAt.replace('T', ' ').split('+')[0]}（台灣時區）
            </p>
          </div>
        </div>
      )}

      {/* 空狀態 */}
      {!script && !loading && (
        <div className="bg-gray-50 border border-dashed border-gray-300 rounded-xl p-10 text-center">
          <Radio className="w-10 h-10 text-gray-300 mx-auto mb-3" />
          <p className="text-gray-500 text-sm font-medium">播報台尚未連線</p>
          <p className="text-gray-400 text-xs mt-1.5 max-w-sm mx-auto">
            請先在「業績黑洞輸入（老闆總控台）」送出業績排名，播報台將自動接收並生成播報稿。
          </p>
        </div>
      )}
    </div>
  );
}
