/**
 * LINE 轉傳台 — 完整功能版
 * - 訂閱 voidRankingsUpdate 自動接收排名並立即生成各組訊息
 * - 各組獨立複製按鈕
 * - 支援自訂前言（附加在每則訊息最前面）
 * - localStorage 持久化，重整後保留
 */
import { useState, useEffect, useCallback } from 'react';
import { MessageSquare, RefreshCw, Copy, Check, ChevronDown, ChevronUp } from 'lucide-react';

interface RankRow {
  rank: number;
  name: string;
  amount: number;
  group?: string;
}

const GROUPS = ['A1', 'A2', 'B', 'C'] as const;

const GROUP_STYLE: Record<string, { card: string; badge: string }> = {
  A1: { card: 'bg-yellow-50 border-yellow-200', badge: 'bg-yellow-100 text-yellow-800 border-yellow-300' },
  A2: { card: 'bg-orange-50 border-orange-200', badge: 'bg-orange-100 text-orange-800 border-orange-300' },
  B:  { card: 'bg-blue-50  border-blue-200',   badge: 'bg-blue-100  text-blue-800  border-blue-300'  },
  C:  { card: 'bg-gray-50  border-gray-200',   badge: 'bg-gray-100  text-gray-700  border-gray-300'  },
};

const LS_KEY = 'lineMessages';

export function LineForwardPage() {
  const [rankings, setRankings] = useState<RankRow[]>([]);
  const [reportDate, setReportDate] = useState('');
  const [messages, setMessages] = useState<Record<string, string>>({});
  const [prefix, setPrefix] = useState('');       // 自訂前言
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState<string | null>(null);
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({});
  const [lastUpdated, setLastUpdated] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // ── 初始：從 localStorage 恢復 ──
  useEffect(() => {
    try {
      const saved = localStorage.getItem(LS_KEY);
      if (saved) setMessages(JSON.parse(saved));
      const savedRankings = localStorage.getItem('voidRankings');
      if (savedRankings) {
        const parsed = JSON.parse(savedRankings);
        if (parsed.rows?.length) {
          setRankings(parsed.rows);
          const now = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Taipei' }).format(new Date());
          setReportDate(now);
          setLastUpdated(new Date(parsed.updatedAt).toLocaleTimeString('zh-TW', { hour12: false }));
        }
      }
    } catch { /* 忽略 */ }
  }, []);

  // ── 監聽 voidRankingsUpdate — 自動接收並生成 ──
  useEffect(() => {
    async function onUpdate(e: Event) {
      const ev = e as CustomEvent<{ rows: RankRow[]; updatedAt: number }>;
      if (!ev.detail?.rows?.length) return;
      const rows = ev.detail.rows;
      setRankings(rows);
      const now = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Taipei' }).format(new Date());
      setReportDate(now);
      setLastUpdated(new Date(ev.detail.updatedAt).toLocaleTimeString('zh-TW', { hour12: false }));
      setAutoGenerated(false);
      try {
        const res = await fetch('/api/v1/system/line-message', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ rankings: rows, reportDate: now }),
        });
        const json = await res.json();
        if (json.success) {
          setMessages(json.data.messages);
          localStorage.setItem(LS_KEY, JSON.stringify(json.data.messages));
          setAutoGenerated(true);
        }
      } catch { /* 靜默 */ }
    }
    window.addEventListener('voidRankingsUpdate', onUpdate);
    return () => window.removeEventListener('voidRankingsUpdate', onUpdate);
  }, []);

  const generate = useCallback(async () => {
    if (!rankings.length) {
      setError('❌ 尚無排名資料，請先在業績黑洞頁送出資料');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/v1/system/line-message', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ rankings, reportDate }),
      });
      const json = await res.json();
      if (json.success) {
        setMessages(json.data.messages);
        localStorage.setItem(LS_KEY, JSON.stringify(json.data.messages));
      } else {
        setError(json.message || '生成失敗');
      }
    } catch {
      setError('❌ 無法連線後端');
    } finally {
      setLoading(false);
    }
  }, [rankings, reportDate]);

  const copyGroup = useCallback((group: string, text: string) => {
    const full = prefix ? `${prefix}\n\n${text}` : text;
    navigator.clipboard.writeText(full).then(() => {
      setCopied(group);
      setTimeout(() => setCopied(null), 2000);
    });
  }, [prefix]);

  const groupCounts = GROUPS.reduce((acc, g) => {
    acc[g] = rankings.filter(r => r.group === g).length;
    return acc;
  }, {} as Record<string, number>);

  const hasMessages = Object.keys(messages).length > 0;

  return (
    <div className="max-w-3xl mx-auto space-y-5 p-6 animate-in fade-in slide-in-from-bottom-4 duration-500">

      {/* 標題 */}
      <div className="pb-4 border-b border-gray-200">
        <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
          <MessageSquare className="w-7 h-7 text-green-500" /> LINE 轉傳台
        </h1>
        <p className="text-gray-500 mt-1 text-sm">
          {lastUpdated
            ? <><span className="text-green-600 font-semibold">● 即時連線</span> — 已接收 {rankings.length} 筆排名（{lastUpdated} 更新）{autoGenerated && <span className="ml-2 text-green-500 text-xs">✦ 已自動生成各組訊息</span>}</>
            : '等待業績資料…請先在業績黑洞頁送出排名'}
        </p>
      </div>

      {/* 分組人數快覽 */}
      {rankings.length > 0 && (
        <div className="grid grid-cols-4 gap-2">
          {GROUPS.map(g => (
            <div key={g} className={`rounded-xl border p-3 text-center ${GROUP_STYLE[g].card}`}>
              <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-bold border ${GROUP_STYLE[g].badge}`}>{g}</span>
              <p className="text-sm font-semibold text-gray-700 mt-1">{groupCounts[g] || 0} 人</p>
            </div>
          ))}
        </div>
      )}

      {/* 自訂前言 */}
      <div className="bg-white rounded-xl border border-gray-200 p-4 space-y-2">
        <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide">自訂前言（可選）</label>
        <textarea
          value={prefix}
          onChange={e => setPrefix(e.target.value)}
          placeholder="例：各組夥伴好！以下是今日派單結果，請確認後接單。"
          rows={2}
          className="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-green-400 resize-none text-gray-700"
        />
        <p className="text-xs text-gray-400">複製時會自動附加在訊息最前面</p>
      </div>

      {/* 錯誤 */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-sm text-red-700">{error}</div>
      )}

      {/* 生成按鈕 */}
      <button
        onClick={generate}
        disabled={loading || !rankings.length}
        className="flex items-center gap-2 px-5 py-2.5 text-sm font-bold text-white bg-gradient-to-r from-green-500 to-emerald-600 rounded-xl shadow-md transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <MessageSquare className="w-4 h-4" />}
        {loading ? '生成中…' : hasMessages ? '重新生成' : '生成 LINE 訊息'}
      </button>

      {/* 各組訊息卡片 */}
      {hasMessages && (
        <div className="space-y-3">
          {GROUPS.filter(g => messages[g]).map(g => {
            const isCollapsed = collapsed[g];
            const style = GROUP_STYLE[g];
            return (
              <div key={g} className={`rounded-2xl border overflow-hidden ${style.card}`}>
                {/* 群組標頭 */}
                <div className="px-5 py-3 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold border ${style.badge}`}>{g} 組</span>
                    <span className="text-sm text-gray-600">{groupCounts[g] || 0} 人</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => copyGroup(g, messages[g])}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-white border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-50 transition-all"
                    >
                      {copied === g ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
                      {copied === g ? '已複製！' : '複製此組'}
                    </button>
                    <button
                      onClick={() => setCollapsed(prev => ({ ...prev, [g]: !prev[g] }))}
                      className="p-1.5 text-gray-400 hover:text-gray-600 transition-colors"
                    >
                      {isCollapsed ? <ChevronDown className="w-4 h-4" /> : <ChevronUp className="w-4 h-4" />}
                    </button>
                  </div>
                </div>
                {/* 訊息內容 */}
                {!isCollapsed && (
                  <div className="px-5 pb-4">
                    <pre className="text-sm text-gray-800 whitespace-pre-wrap font-sans leading-relaxed bg-white rounded-xl p-4 border border-white/60">
                      {prefix ? `${prefix}\n\n${messages[g]}` : messages[g]}
                    </pre>
                  </div>
                )}
              </div>
            );
          })}

          {/* 一鍵複製全部 */}
          <button
            onClick={() => {
              const all = GROUPS.filter(g => messages[g])
                .map(g => (prefix ? `${prefix}\n\n${messages[g]}` : messages[g]))
                .join('\n\n' + '─'.repeat(20) + '\n\n');
              navigator.clipboard.writeText(all).then(() => {
                setCopied('ALL');
                setTimeout(() => setCopied(null), 2000);
              });
            }}
            className="w-full py-2.5 text-sm font-semibold text-green-700 bg-green-50 border border-green-200 rounded-xl hover:bg-green-100 transition-all flex items-center justify-center gap-2"
          >
            {copied === 'ALL' ? <><Check className="w-4 h-4" /> 全組已複製！</> : <><Copy className="w-4 h-4" /> 一鍵複製全組訊息</>}
          </button>
        </div>
      )}

      {/* 空狀態 */}
      {!hasMessages && !loading && (
        <div className="bg-gray-50 border border-dashed border-gray-300 rounded-xl p-10 text-center">
          <MessageSquare className="w-10 h-10 text-gray-300 mx-auto mb-3" />
          <p className="text-gray-500 text-sm font-medium">LINE 轉傳台尚未連線</p>
          <p className="text-gray-400 text-xs mt-1.5 max-w-sm mx-auto">
            請先在「業績黑洞輸入（老闆總控台）」送出業績排名，此頁會自動接收並依 A1/A2/B/C 分組生成轉傳訊息。
          </p>
        </div>
      )}
    </div>
  );
}
