module.exports = Object.freeze({
  OK: 'OK',
  PARSE_SUCCESS: 'PARSE_SUCCESS',
  PARSE_FAILED: 'PARSE_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  REBUILD_SUCCESS: 'REBUILD_SUCCESS'
});
